# Generated by Django 5.1.7 on 2025-03-26 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(max_length=50)),
                ('C_Price', models.IntegerField(null=True)),
                ('C_Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Categories_Type1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_number', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categories_Type2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_number', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categories_Type3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_number', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categories_Type4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_number', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categories_Type5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_number', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categories_Type6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_number', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categories_Type7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_number', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Homee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='T_Home2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_Name', models.CharField(max_length=50)),
                ('T_Price', models.IntegerField(null=True)),
                ('T_Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_Name', models.CharField(max_length=50)),
                ('H_Price', models.IntegerField(null=True)),
                ('H_Image', models.ImageField(null=True, upload_to='')),
                ('H_serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.homee')),
            ],
        ),
        migrations.CreateModel(
            name='Type1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name1', models.CharField(max_length=50)),
                ('Category_Price', models.IntegerField()),
                ('Category_Image', models.ImageField(null=True, upload_to='')),
                ('Serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.categories_type1')),
            ],
        ),
        migrations.CreateModel(
            name='Type2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name2', models.CharField(max_length=50)),
                ('Category_Price', models.IntegerField()),
                ('Category_Image', models.ImageField(null=True, upload_to='')),
                ('Serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.categories_type2')),
            ],
        ),
        migrations.CreateModel(
            name='Type3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name2', models.CharField(max_length=50)),
                ('Category_Price', models.IntegerField()),
                ('Category_Image', models.ImageField(null=True, upload_to='')),
                ('Serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.categories_type3')),
            ],
        ),
        migrations.CreateModel(
            name='Type4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name2', models.CharField(max_length=50)),
                ('Category_Price', models.IntegerField()),
                ('Category_Image', models.ImageField(null=True, upload_to='')),
                ('Serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.categories_type4')),
            ],
        ),
        migrations.CreateModel(
            name='Type5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name2', models.CharField(max_length=50)),
                ('Category_Price', models.IntegerField()),
                ('Category_Image', models.ImageField(null=True, upload_to='')),
                ('Serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.categories_type5')),
            ],
        ),
        migrations.CreateModel(
            name='Type6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name2', models.CharField(max_length=50)),
                ('Category_Price', models.IntegerField()),
                ('Category_Image', models.ImageField(null=True, upload_to='')),
                ('Serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.categories_type6')),
            ],
        ),
        migrations.CreateModel(
            name='Type7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name2', models.CharField(max_length=50)),
                ('Category_Price', models.IntegerField()),
                ('Category_Image', models.ImageField(null=True, upload_to='')),
                ('Serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.categories_type7')),
            ],
        ),
    ]
