# Generated by Django 5.1.4 on 2024-12-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_Name', models.CharField(max_length=50)),
                ('H_Price', models.IntegerField()),
                ('H_Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
