# Generated by Django 5.1.4 on 2024-12-31 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='H_Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='H_serial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecomapp.homee'),
        ),
    ]
