# Generated by Django 5.1.4 on 2024-12-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0002_homee_alter_home_h_price_home_h_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homee',
            name='Price',
        ),
    ]
