# Generated by Django 5.1.4 on 2024-12-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0003_remove_homee_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='H_Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
