# Generated by Django 5.1.4 on 2025-01-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0005_alter_home_h_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_Name', models.CharField(max_length=50)),
                ('T_Price', models.IntegerField(null=True)),
                ('T_Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
