# Generated by Django 5.1.4 on 2025-01-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0006_t_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T_categories',
            new_name='T_Home2',
        ),
    ]
