# Generated by Django 5.1.4 on 2025-01-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0007_rename_t_categories_t_home2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(max_length=50)),
                ('C_Price', models.IntegerField(null=True)),
                ('C_Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
