# Generated by Django 5.1.4 on 2025-01-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0008_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriestype1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1_Name', models.CharField(max_length=50)),
                ('c1_Price', models.IntegerField(null=True)),
                ('c1_Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
