# Generated by Django 5.1.4 on 2025-01-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0009_categoriestype1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriestype1',
            old_name='c1_Image',
            new_name='C1_Image',
        ),
        migrations.RenameField(
            model_name='categoriestype1',
            old_name='c1_Price',
            new_name='C1_Price',
        ),
    ]
