# Generated by Django 5.1.4 on 2025-01-23 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0010_rename_c1_image_categoriestype1_c1_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Type1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_number', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name1', models.CharField(max_length=50)),
                ('Category_Price', models.IntegerField()),
                ('Category_Image', models.ImageField(null=True, upload_to='')),
                ('Serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecomapp.categories_type1')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoriestype1',
        ),
    ]
