# Generated by Django 5.1.4 on 2025-01-25 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0013_categories_type3_type3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Type4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_number', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name2', models.CharField(max_length=50)),
                ('Category_Price', models.IntegerField()),
                ('Category_Image', models.ImageField(null=True, upload_to='')),
                ('Serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecomapp.categories_type3')),
            ],
        ),
    ]
